### ISSUE TITLE
TODO till September

### ISSUE THREAD

**Issue by MariusVanDerWijden** [MariusVanDerWijden/gpusnarks#11]
Stuff left to do:

- [ ] Use pinned host memory
- [ ] Use asynchronous memcopies
- [ ] Write CPU test code
